; AHK 1.1.33.02
; Built 09/12/2020

version = 0.1

; Install the seeding file from the executable
FileInstall, config\GameUserSettings.ini.seeding, C:\Users\%A_UserName%\AppData\Local\SquadGame\Saved\Config\WindowsNoEditor\GameUserSettings.ini.seeding, 1

; Generated by AutoGUI 2.6.2
; Build GUI for user interactions
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui -MaximizeBox
Gui Add, Button, gafkseed x96 y64 w200 h50, &AFK Seed
Gui Add, Button, grestore x96 y128 w200 h50, &Quit Squad and Restore Settings
Gui Add, Text, vtxtStatus x5 y0 w390 h40 +0x200, Status: %status%
Gui Add, Text, x304 y8 w120 h23 +0x200, Version: %version%

Gui Show, w400 h200, Squad AFK Seeding Helper
Return

afkseed(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {
    ; check to see if the backup file already exists, if so game was closed outside of script and we don't want to overwrite users' settings
    if FileExist( "C:\Users\%A_UserName%\Local\SquadGame\Saved\Config\WindowsNoEditor\GameUserSettings.ini.backup" ) {
        Goto, launchgame
    }

    ; Copy the users' settings to a backup file, then copy seeding settings to the normal file    
    FileCopy, C:\Users\%A_UserName%\AppData\Local\SquadGame\Saved\Config\WindowsNoEditor\GameUserSettings.ini, C:\Users\%A_UserName%\AppData\Local\SquadGame\Saved\Config\WindowsNoEditor\GameUserSettings.ini.backup, 1
    FileCopy, C:\Users\%A_UserName%\AppData\Local\SquadGame\Saved\Config\WindowsNoEditor\GameUserSettings.ini.seeding, C:\Users\%A_UserName%\AppData\Local\SquadGame\Saved\Config\WindowsNoEditor\GameUserSettings.ini, 1
    
    ; Start Squad on Bloody Bucket's primary server
    ; May change this in the future to ask the user which server to join.
    launchgame:
    run, steam://connect/chi1-squad1.bloodybucket.net:27165

    ; Wait 30 seconds, then minimize Squad
    Sleep, 30000
    WinMinimize, SquadGame
}

restore(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {
    ; Close Squad
    WinClose, SquadGame
    ; Restore the backup settings to the normal file
    FileCopy, C:\Users\%A_UserName%\AppData\Local\SquadGame\Saved\Config\WindowsNoEditor\GameUserSettings.ini.backup, C:\Users\%A_UserName%\Local\SquadGame\Saved\Config\WindowsNoEditor\GameUserSettings.ini, 1
    ; Delete the backup and seeding file to prepare for next launch
    FileDelete, C:\Users\%A_UserName%\AppData\Local\SquadGame\Saved\Config\WindowsNoEditor\GameUserSettings.ini.backup
    FileDelete, C:\Users\%A_UserName%\AppData\Local\SquadGame\Saved\Config\WindowsNoEditor\GameUserSettings.ini.seeding
}

GuiEscape:
GuiClose:
    ExitApp
