; AHK 1.1.33.02
; Created by Travis Cochran (DiscoveryOV, Bloody Bucket)
; Released under GPL-3.0

version = 0.2b

; Create app folder in Documents
FileCreateDir, %A_MyDocuments%\SquadAFKSeedHelper\
FileCreateDir, %A_MyDocuments%\SquadAFKSeedHelper\settings\


; Install the seeding file from the executable
FileInstall, config\GameUserSettings.ini.seeding, %A_MyDocuments%\SquadAFKSeedHelper\settings\GameUserSettings.ini.seeding, 1

; Install servers.ini and read it
;FileInstall, config\servers.ini, %A_MyDocuments%\SquadAFKSeedHelper\servers.ini
;IniRead, servers, %A_MyDocuments%\SquadAFKSeedHelper\servers.ini, BloodyBucket, Servers


; Generated by AutoGUI 2.6.2
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Add, Button, gafkseed x96 y40 w200 h50, &AFK Seed
Gui Add, Button, grestore x96 y104 w199 h50, &Quit Squad
Gui Add, Text, x10 y174 w120 h20, %version%
Gui Add, Link, x312 y176 w80 h20, <a href="https://github.com/DiscoveryOV/SquadAFKSeedHelper">View on GitHub</a>

Gui Show, w400 h200, Squad AFK Seeding Helper
Return

afkseed(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {
    #Include, res/afkseed.ahk
}

restore(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {
    #Include, res/restore.ahk
}

GuiEscape:
GuiClose:
    ExitApp
